#!/usr/bin/env python3
"""Generate assets/com.kayab.netmedic.policy from action_catalog.ACTIONS.

M8: the policy XML is a build artifact of the ActionSpec table, not a
hand-maintained fifth registry. Edit the table, re-run with --write
(or run the --check step in CI to catch drift).

Usage:
    scripts/generate_policy.py --check   # exit 1 on drift (CI)
    scripts/generate_policy.py --write   # regenerate the asset
"""

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "netmedic"))

from netmedic.action_catalog import ACTIONS  # noqa: E402

POLICY_PATH = REPO / "assets" / "com.kayab.netmedic.policy"
HELPER_PATH = "/usr/libexec/netmedic/helper"
VENDOR_URL = "https://github.com/kayab999/netmedic-linux"

HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policyconfig PUBLIC
 "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/PolicyKit/1/policyconfig.dtd">
<policyconfig>
  <vendor>Kayab Software</vendor>
  <vendor_url>%s</vendor_url>

  <!--
    GENERATED by scripts/generate_policy.py from action_catalog.ACTIONS.
    Do not edit by hand: edit the table and regenerate with the script.
    Install wrapper at /usr/libexec/netmedic/helper via
    scripts/install-polkit-policy.sh.
  -->

""" % VENDOR_URL

ACTION_TMPL = """  <action id="%(id)s">
    <description>%(description)s</description>
    <message>%(message)s</message>
    <defaults>
      <allow_any>auth_admin</allow_any>
      <allow_inactive>auth_admin</allow_inactive>
      <allow_active>%(allow_active)s</allow_active>
    </defaults>
    <annotate key="org.freedesktop.policykit.exec.path">%(helper)s</annotate>
    <annotate key="org.freedesktop.policykit.exec.argv1">%(verb)s</annotate>
    <annotate key="org.freedesktop.policykit.exec.allow_gui">true</annotate>
  </action>
"""


def render() -> str:
    parts = [HEADER]
    first = True
    for spec in ACTIONS:
        if spec.polkit_id is None:
            continue
        assert spec.helper_verb is not None and spec.message, spec
        if not first:
            parts.append("\n")
        first = False
        parts.append(ACTION_TMPL % {
            "id": spec.polkit_id,
            "description": spec.description,
            "message": spec.message,
            "allow_active": "auth_admin_keep" if spec.keep_auth else "auth_admin",
            "helper": HELPER_PATH,
            "verb": spec.helper_verb,
        })
    parts.append("</policyconfig>\n")
    return "".join(parts)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--check", action="store_true", help="exit 1 if asset drifts")
    group.add_argument("--write", action="store_true", help="regenerate the asset")
    args = parser.parse_args(argv)

    rendered = render()
    current = POLICY_PATH.read_text(encoding="utf-8")
    if args.write:
        POLICY_PATH.write_text(rendered, encoding="utf-8")
        print(f"wrote {POLICY_PATH}")
        return 0
    if rendered != current:
        print(f"DRIFT: {POLICY_PATH} does not match action_catalog.ACTIONS; run --write")
        return 1
    print("policy in sync")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
