[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "netmedic"
version = "1.1.0"
authors = [
    { name = "Kayab Software", email = "support@kayabsoftware.com" },
]
description = "Professional network diagnostics, repair, and infrastructure management for Linux."
requires-python = ">=3.8"
dependencies = [
    "PyGObject",
    "pillow",
]

[project.scripts]
netmedic = "netmedic.app:main"

[project.optional-dependencies]
ai = [
    "llama-cpp-python>=0.2.57"
]
